chat/urls.py
from django.urls import path

from .views import *

app_name="chat"
urlpatterns = [
    path('', index, name='index'),
    path('<str:room_name>/',room, name='room'),
]

ngo/urls.py
from django.urls import path, include
from .views import *

app_name = "ngo"
urlpatterns = [
    path('', index, name="index"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('events/', events, name="events"),
    path('event/<slug:slug>/', event_details, name="event"),
    path('blog/', blog, name="blog"),
    path('blog/<slug:slug>/', post_details, name="post"),
    path('projects/', projects, name="projects"),
    path('project/<slug:slug>/', project_details, name="project"),
    path('search/', search, name="search"),
    path('gallery/', gallery, name="gallery"),
    path('become-a-member/', join, name="join"),
    path('subscribe/', subscribe, name="subscribe"),
    path('unsubscribe/<email>/', unsubscribe, name="unsubscribe"),
]

vauth/urls.py
from django.urls import path, re_path
from .views import *

app_name = "vauth"
urlpatterns = [
    path('login/', mylogin, name="login"),
    path('dashboard/', dashboard, name="dashboard"),
    path('analytics/', analytics, name="analytics"),
    path('profile/', profile, name="profile"),
    path('dp/', dp, name="dp"),
    path('posts/', posts, name="posts"),
    path('edit-post/<slug:slug>/', edit_post, name="edit_post"),
    path('tasks/', tasks, name="tasks"),
    path('complete-task/<int:task_id>/', complete_task, name="complete_task"),
    path('newsletter/', newsletter, name="newsletter"),
    path('ajax-donations/', ajax_donations, name="ajax_donations"),
    path("ajax-visitors/", ajax_visitors, name="ajax_visitors"),
    #####################
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
]

ngo/models.py
from django.db import models
from django.shortcuts import reverse, redirect
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from ckeditor.fields import RichTextField
from .utils import image_resize

TYPES = (
    ('P', 'Post'),
    ('PR', 'Project')
)

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    cat_type = models.CharField(max_length=100, choices=TYPES)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("ngo:category", kwargs={"slug": self.slug})
    class Meta:
        verbose_name_plural = "Categories"

class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    tags = TaggableManager()
    content = RichTextField()
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    cover = models.ImageField(upload_to="posts/")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("ngo:post", kwargs={"slug": self.slug})
    class Meta:
        ordering  = ['-created']
    
    def save(self, *args, **kwargs):
        image_resize(self.cover, 950,950)
        super().save(*args, **kwargs)
    

class Event(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    tags = TaggableManager()
    content = RichTextField()
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    due_datetime = models.DateTimeField(blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    embed_script = models.CharField(max_length=255, blank=True, null=True)
    cover = models.ImageField(upload_to="events/")

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("ngo:event", kwargs={"slug": self.slug})
    class Meta:
        ordering  = ['-due_datetime']

    def save(self, *args, **kwargs):
        image_resize(self.cover, 950,950)
        super().save(*args, **kwargs)


class Project(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    tags = TaggableManager()
    content = RichTextField()
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    cover = models.ImageField(upload_to="projects/")
    raised = models.FloatField()
    goal = models.FloatField()

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("ngo:project", kwargs={"slug": self.slug})
    class Meta:
        ordering  = ['-created']

    def save(self, *args, **kwargs):
        image_resize(self.cover, 950,950)
        super().save(*args, **kwargs)

class Image(models.Model):
    name = models.CharField(max_length=100)
    source = models.ImageField()
    description = models.TextField()
    published = models.DateTimeField(auto_now_add=True, db_index=True)
    def __str__(self):
        return self.name
    class Meta:
        ordering  = ['-published']

    def save(self, *args, **kwargs):
        image_resize(self.source, 950,950)
        super().save(*args, **kwargs)

class Subscriber(models.Model):
    email = models.EmailField(max_length=254, unique=True)

# def post_reciever(sender, instance, created, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = instance.title.replace(' ', '-').strip("('')").lower()

# pre_save.connect(post_reciever, sender=User)
# def save(self, *args, **kwargs):
#     try:
#         this = MyModelName.objects.get(id=self.id)
#         if this.MyImageFieldName != self.MyImageFieldName:
#             this.MyImageFieldName.delete()
#     except: pass
#     super(MyModelName, self).save(*args, **kwargs)

vauth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from taggit.models import Tag
from chat.models import Contact
from ckeditor.fields import RichTextField
from .utils import user_signal, get_client_ip


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    verified = models.BooleanField(default=False)
    sex = models.CharField(max_length=10)
    about = models.TextField(blank=True, null=True)
    phone_number = models.CharField(max_length=12, blank=True, null=True)
    dp = models.ImageField(upload_to="display_pics/", blank=True, null=True)
    location = models.CharField(max_length=100)
    position = models.CharField(max_length=100, default="Member", blank=True, null=True)
    date_joined = models.DateTimeField(auto_now_add=True, db_index=True)
    subscribed = models.BooleanField(default=False, blank=True)
    class Meta:
        ordering = ['-date_joined']
    def delete(self, *args, **kwargs):
        self.dp.delete()
        super().delete(*args, **kwargs)
    # def save(self, *args, **kwargs):
    #     super().full_clean(*args, **kwargs)
    #     super().save(*args, **kwargs)


class Applicant(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    statement = models.TextField()
    middle_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, unique=True)
    phone_number = models.CharField(max_length=12, blank=True, null=True)
    address = models.CharField(max_length=100)
    sex = models.CharField(max_length=10)
    date_applied = models.DateTimeField(auto_now_add=True, db_index=True)
    class Meta:
        ordering = ['-date_applied']

class Task(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    completed = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    class Meta:
        ordering = ['-timestamp']

def profile_reciever(sender, instance, created, *args, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        Contact.objects.create(user=instance)


post_save.connect(profile_reciever, sender=User)

# class Visitor(models.Model):
#     user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
#     ip_address = models.CharField(max_length=120)
#     timestamp = models.DateTimeField(auto_now_add=True)

# def user_receiver(sender, instance, request, *args, **kwargs):
#     user = instance
#     ip_address = get_client_ip(request)
#     ip_qs = Visitor.objects.filter(ip_address=ip_address)
#     if not ip_qs.exists():
#         user_session = Visitor.objects.create(ip_address=ip_address)
#         if user.is_authenticated:
#             print(Visitor.objects.exists())
#             if Visitor.objects.exists():
#                 if not Visitor.objects.filter(user=user).exists():
#                     user_session.user = user
#         user_session.save()

# user_signal.connect(user_receiver)

vauth/forms.py
from django import forms
from .validators import validate_file_extension
from django.contrib.auth.models import User
from django.forms import ModelForm
from ngo.views import Post
from ckeditor.widgets import CKEditorWidget

class ProfileForm(ModelForm):
    location = forms.CharField(required=False)
    about = forms.CharField(required=False, widget=forms.Textarea())
    phone_number = forms.CharField(required=False)
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
    def save(self, commit=True):
        user = self.instance
        user.profile.location = self.cleaned_data['location']
        user.profile.about = self.cleaned_data['about']
        user.profile.phone_number = self.cleaned_data['phone_number']
        user.profile.save()
        if commit:
            return super(ProfileForm, self).save()



    # def clean(self):
    #     cleaned_data = super().clean()
    #     username = cleaned_data.get("username")
    #     users = User.objects.all()
    #     if username and subject and "help" not in subject:
    #         msg = "Must put 'help' in subject when cc'ing yourself."
    #         self.add_error('username', msg)
    #         self.add_error('subject', msg)
    
class PostForm(ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    cover = forms.ImageField(validators=[validate_file_extension], required=False)
    class Meta:
        model = Post
        # fields = [ 'title', 'tags', 'quote', 'content', 'cover', 'category']
        exclude = ['created', 'slug', 'author']

class NewsletterForm(forms.Form):
    title = forms.CharField()
    body = forms.CharField(widget=CKEditorWidget())

class PictureForm(forms.Form):
    picture = forms.ImageField(validators=[validate_file_extension])

class LoginForm(forms.Form):
    username= forms.CharField()
    password = forms.CharField(widget=(forms.PasswordInput()))
    remember = forms.CharField(widget=(forms.CheckboxInput))

templates/vauth/base.html
{% load static %}
{% load tasks %}
{% load contact_chats %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon -->
    <link rel="icon" href="{% static 'ngo/img/core-img/pluv2.png' %}">
    <!-- Core Stylesheet -->
    <link rel="stylesheet" href="{% static 'ngo/style.css' %}">
    {% block head %}{% endblock %}
 
</head>
<body class="bg-ash">

        {% if messages %}
        {% for message in messages %}
                <!-- Position it -->
                <div class="toast-container">
                    <div class="toast animated slideInRight bg-{{message.tags}} mr-2 mt-2" role="alert" aria-live="assertive" aria-atomic="true" id="toast" data-autohide="false">
                    <div class="toast-body">
                    <button type="button" class="close text-light" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                        <p class="text-light mb-0">{{message|safe}}</p>
                    </div>
                    </div>
                </div>
                
        {% endfor %}
    {% endif %}
    <nav class="navbar navbar-expand-md navbar-light dashboard-navbar fixed-top bg-light">
        <div class="container-fluid">
            <button class="btn dashboard-btn" type="button" data-toggle="slide-collapse" data-target="#slide-out">
                <i class="navbar-toggler-icon"></i>
              </button>
              <a href="{% url 'ngo:index' %}" class="mr-auto"><img src="{% static 'ngo/img/core-img/pluv.png' %}" alt="" class="brand-img mr-auto d-none d-sm-inline-block"></a>
          
            <div class="" id="navbarsExample04">
              <ul class="navbar-nav">
                  <li class="nav-item dropdown ml-2">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                      <b class="ti ti-user"></b> <span class="clearfix d-none d-sm-inline-block">Profile</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                      <a class="dropdown-item" href="{% url 'vauth:profile' %}">Edit profile</a>
                      <a class="dropdown-item" href="{% url 'password_change' %}">Password Change</a>
                      <a class="dropdown-item" href="{% url 'logout' %}"><i class="mr-2 fa fa-sign-out"></i>Log Out</a>
                    </div>
                  </li>
                <li class="nav-item ml-2">
                <a class="nav-link" href="{% url 'ngo:index' %}">
                    <i class="fa fa-home"></i>
                    <span class="d-none d-md-inline-block">Home</span>
                </a>
                </li>
              </ul>
              
            </div>
        </div>
    </nav>

    <main class="dashboard">
        <!-- Sidebar navigation -->
        <div id="slide-out" class="sidenav fixed bg-dark-crose">
            <br>
            <ul class="nav flex-column">
                <div class="side-nav-title mb-4">
                    <button type="button" class="close text-light text-lg mt-1 mr-3" data-dismiss="close" aria-label="Close" data-target="#slide-out">
                    <span aria-hidden="true">&times;</span>
                    </button>
                    <a href="{% url 'ngo:index' %}"><img src="{% static 'ngo/img/core-img/logo2.png' %}" alt="" class=" ml-2 mr-auto"></a>
                </div>
                {% comment %} <form class="form-inline my-2 my-md-0">
                    <input class="form-control" type="text" placeholder="Search">
                </form> {% endcomment %}
                
                <li class="nav-item mt-4">
                <a class="nav-link text-light {% block dashboard %}{% endblock %}" href="{% url 'vauth:dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item">
                <a class="nav-link text-light {% block profile %}{% endblock %}" href="{% url 'vauth:profile' %}">Profile</a>
                </li>
                <li class="nav-item">
                <a class="nav-link text-light {% block tasks %}{% endblock %}" href="{% url 'vauth:tasks' %}">Tasks</a>
                </li>
                <li class="nav-item">
                <a class="nav-link text-light {% block posts %}{% endblock %}" href="{% url 'vauth:posts' %}"> Your Posts</a>
                </li>
                {% if user.is_superuser %}
                <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'vauth:newsletter' %}">Send A Newsletter</a>
                </li>
                <li class="nav-item">
                <a class="nav-link text-light" href="{% url 'vauth:analytics' %}">Analytics</a>
                </li>
                {% endif %}
                {% comment %} <hr class="bg-light my-0">
                <li class="nav-item" id="accordianId" role="tablist" aria-multiselectable="true">
                    <a data-toggle="collapse" class="nav-link text-light {% block chat %}{% endblock %}" data-parent="#accordianId" href="#chats" aria-expanded="true" aria-controls="chats">
                    Chat Rooms
                    </a>
                </li>
                <div id="chats" class="collapse in" role="tabpanel" aria-labelledby="section1HeaderId">
                    {% for chat in user|get_contact_chats %}
                    <li class="nav-item">
                    <a href="{% url 'chat:room' chat.name %}" class="nav-link text-light chat-item"><i class="fa fa-chevron-right" aria-hidden="true"></i> {{chat.name}}</a>
                    </li>
                    {% endfor %}
                </div>
                <hr class="bg-light my-0"> {% endcomment %}
            </ul>
        </div>
        <!--/. Sidebar navigation -->
        {% block body %}{% endblock %}
        <div class="sidenav-overlay" data-target="#slide-out"></div>
    </main>
    <script src="{% static 'ngo/js/jquery/jquery-2.2.4.min.js' %}"></script>
    <!-- Bootstrap js -->
    <script src="{% static 'ngo/js/wow.min.js' %}"></script>
    <script src="{% static 'ngo/js/bootstrap/bootstrap.js' %}"></script>
    <script src="{% static 'ngo/js/active.js' %}"></script>

    {% block js%}{% endblock %}
</body>
</html>

templates/vauth/dashboard.html
{% extends 'vauth/base.html' %}
{% load static %}
{% load tasks %}
{% block title %}Dashboard{% endblock %}
{% block dashboard %}active{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row bg-ash">
        <div class="col-lg-4 mb-4">
            <div class="card mb-4">
            {% if user.profile.dp %}
              <div class="mx-auto rounded-circle avatar mt-n7" style="background-image: url('{{user.profile.dp.url}}')">
                <div class="img-overlay w-100 h-100 rounded-circle text-white text-center"><i class="fa fa-2x fa-camera mt-auto" aria-hidden="true"></i> </div>
              </div>
              
            {% else %}
              <div class="mx-auto rounded-circle avatar bg-info mt-n7" style="background-image: url('{% if user.profile.sex|lower == 'male'%}{% static 'ngo/img/avatars/male.png' %}{% else %}{% static 'ngo/img/avatars/female.png' %}{% endif %}')">
                <div class="img-overlay w-100 h-100 rounded-circle text-white text-center"><i class="fa fa-2x fa-camera mt-auto" aria-hidden="true"></i> </div>
              </div>
            {% endif %}
              <form action="{% url 'vauth:dp' %}" method="POST" enctype="multipart/form-data" class="picture-form">
              {% csrf_token %}
                  <input type="file" name="picture" id="id_picture" style="display: none;" accept="image/png,image/jpeg">
              </form>
                <div class="card-body text-center">
                  <!-- Title -->
                  <h4 class="card-title text-center"><strong>{{user.first_name}} {{user.last_name}}</strong></h4>
                  <h5>{{user.profile.position}} @ <a href="#">PLUV Foundation</a></h5>
                  <p class="dark-grey-text">{{user.profile.location}}</p>

                  <!-- Social -->
                  <a type="button" class="btn-floating btn-small"><i class="fa fa-facebook-f grey-text"></i></a>
                  <a type="button" class="btn-floating btn-small"><i class="fa fa-twitter grey-text"></i></a>
                  <a type="button" class="btn-floating btn-small"><i class="fa fa-linkedin grey-text"></i></a>

                  <!-- Text -->
                  <p class="card-text mt-3">{{user.profile.about}}</p>

                </div>
            </div>
            {% if user.task_set.all %}
              <div class="card mb-4">
                  <div class="card-body">
                      <h4 class="card-title">Tasks</h4>
                      <p class="">
                          {% for task in user.task_set.all|filter_tasks %}
                            {% if forloop.counter < 3 %}
                                <a class="" href="#">
                                    <i class="fa fa-tasks mr-2" aria-hidden="true"></i>
                                    <span>{{task.title|truncatechars:20}}</span>
                                    <span class="float-right"><i class="far fa-clock" aria-hidden="true"></i> {{task.timestamp|time}}</span>
                                </a>
                            {% endif %}
                          {% endfor %}
                      </p>
                      <a href="{% url 'vauth:tasks' %}" class="btn crose-btn bg-info  btn-block">See Tasks</a>
                  </div>
              </div>
            {% endif %}
            <div class="card mb-4">
                <div class="card-body">
  
                  <h5 class="text-center mb-4"><strong>{{user.first_name}}'s Contributions </strong></h5>
  
                  <ul class="list-unstyled pt-4">
                    <li><p>Posts <span class="badge badge-info pull-right">{{user.post_set.count}}</span></p></li>
                    <hr>
                    <li><p>Completed Tasks <span class="badge badge-info pull-right">{{user.task_set.all|verified}}</span></p></li>
                    <hr>
                    <li><p>Incompleted Tasks <span class="badge badge-info pull-right">{{user.task_set.all|tasks_count}}</span></p></li>
                    <hr>
                    <li><p>Total Tasks <span class="badge badge-info pull-right">{{user.task_set.all.count}}</span></p></li>
  
                  </ul>
  
                </div>
              </div>
        </div>
        <!-- work -->
        <div class="col-lg-8">
          <h4 class="text-center">Your Posts</h4><hr>
          <div class="row">
            {% for post in posts %}
              <div class="col-md-6 mb-4">
                <div class="card">
                  <img class="card-img-top img-fluid" src="{{post.cover.url}}" alt="">
                  <div class="card-body">
                    <h3 class="card-title">{{post.title}}</h3>
                    <p class="card-text">{{post.content|safe|truncatechars:"100"}}</p>
                  </div>
                  <div class="card-footer bg-light">
                          <span class="float-left">
                              <a><i class="fa fa-share-alt btn-sm btn btn-clear"></i></a>
                              <a href="{% url 'vauth:edit_post' post.slug %}"><i class="fa fa-pencil btn-sm btn btn-clear"></i></a>
                            </span>
                            <span class="float-right">
                              <a href="{{post.get_absolute_url}}" class="">Live Preview <i class="fa fa-image ml-1 btn btn-clear"></i></a>
                            </span>
                      </div>
                </div>
              </div>
            {% endfor %}
          </div>
          <a href="{% url 'vauth:posts' %}" class="float-right crose-btn bg-info text-center">See more &raquo;</a>
        <!-- work -->
        
    </div>
    
</div>

{% endblock %}

templates/vauth/profile.html
{% extends 'vauth/base.html' %}
{% load static %}
{% block title %}Profile{% endblock %}
{% block profile %}active{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 mb-4 col-md-4">
            <div class="card mb-4">
                <div class="card-header mt-n4 mx-4 bg-crose mb-4 rounded">Edit Display Picture</div>
                  {% if user.profile.dp %}
                    <div class="mx-auto rounded-circle avatar" style="background-image: url('{{user.profile.dp.url}}');">
                    <div class="img-overlay w-100 h-100 rounded-circle text-white text-center"><i class="fa fa-2x fa-camera mt-auto" aria-hidden="true"></i> </div>
                    </div>
                  {% else %}
                    <div class="mx-auto rounded-circle avatar bg-info" style="background-image: url('{% if user.profile.sex|lower == 'male'%}{% static 'ngo/img/avatars/male.png' %}{% else %}{% static 'ngo/img/avatars/female.png' %}{% endif %}')">
                    <div class="img-overlay w-100 h-100 rounded-circle text-white text-center"><i class="fa fa-2x fa-camera mt-auto" aria-hidden="true"></i> </div>
                    </div>
                  {% endif %}
                <form action="{% url 'vauth:dp' %}" method="POST" enctype="multipart/form-data" class="picture-form">
                {% csrf_token %}
                    <input type="file" name="picture" id="id_picture" style="display: none;" accept="image/png,image/jpeg">
                </form>
                
                <div class="card-body text-center">
                    <!-- Title -->
                    <h4 class="card-title"><strong>{{user.get_full_name}}</strong></h4>
                    <h5 class="">{{user.profile.position}}<a href=""> @ PLUV Foundation</a></h5>
                    <p class="dark-grey-text">{% if user.profile.location %}{{user.profile.location}}{% endif %}</p>
                    <!-- Social -->
                    <div class="">
                        <a type="button" class="btn-floating btn-small"><i class="fa fa-facebook-f grey-text"></i></a>
                        <a type="button" class="btn-floating btn-small"><i class="fa fa-twitter grey-text"></i></a>
                        <a type="button" class="btn-floating btn-small"><i class="fa fa-linkedin grey-text"></i></a>
                    </div>
                    <!-- Text -->
                    <p class="card-text mt-3">{% if user.profile.about %}{{user.profile.about}}{% endif %}</p>
                </div>
            </div>
        </div>
        <!-- work -->
        <div class="col-mlg-8 col-md-8">
        <div class="card">
            <div class="card-header cus-header mt-n4 mr-4 ml-4 bg-crose rounded"> Edit Profile</div>
            <div class="card-body">
                <form action="{% url 'vauth:profile' %}" method="POST">
                  {% csrf_token %}
                    <!-- First row -->
  
                    <div class="row">
  
                      <!-- First column -->
                      <div class="col-md-6">
                        <div class="form-label-group">
                          <input type="text" id="form1" class="form-control validate" value="PLUV Foundation" disabled="">
                          <label for="form1" class="active">Organization</label>
                        </div>
                      </div>
                      <!-- Second column -->
                      <div class="col-md-6">
                        <div class="form-label-group">
                          <input type="text" id="id_username" class="form-control validate" name="username" autofocus placeholder="Username" value="{{user.username}}">
                          <label for="id_username">Username</label>
                        </div>
                      </div>
                    </div>
                    <!-- First row -->
  
                    <!-- First row -->
                    <div class="row">
                      <!-- First column -->
                      <div class="col-md-6">
                        <div class="form-label-group">
                          <input type="text" id="id_first_name" class="form-control validate" name="first_name" placeholder="First Name" value="{{user.first_name}}">
                          <label for="id_first_name">First name</label>
                        </div>
                      </div>
  
                      <!-- Second column -->
                      <div class="col-md-6">
                        <div class="form-label-group">
                          <input type="text" id="id_last_name" name="last_name" class="form-control validate" placeholder="Last Name" value="{{user.last_name}}">
                          <label for="id_last_name">Last name</label>
                        </div>
                      </div>
                    </div>
                    <!-- First row -->
  
                    <!-- Second row -->
                    <div class="row">
  
                      <!-- First column -->
                      <div class="col-md-6">
                        <div class="form-label-group">
                          <input type="email" id="id_email" name="email" class="form-control validate" placeholder="Email Address" value="{{user.email}}">
                          <label for="id_email">Email address</label>
                        </div>
                      </div>
                      <!-- Second column -->
  
                      <div class="col-md-6">
                        <div class="form-label-group">
                          <input type="text" id="id_phone_number" name="phone_number" class="form-control validate" placeholder="Phone Number" value="{{user.profile.phone_number}}">
                          <label for="id_phone_number">Phone Number</label>
                        </div>
                      </div>
                    </div>
                    <!-- Second row -->

                    <!-- Location row -->
                    <div class="row">
  
                      <!-- First column -->
                      <div class="col-md-12">
                        <div class="form-label-group">
                          <input type="text" id="id_location" class="form-control validate" name="location" placeholder="Location" value="{{user.profile.location}}">
                          <label for="id_location">Location</label>
                        </div>
                      </div>
                    </div>
                    <!-- Location row -->
  
                    <!-- Third row -->
                    <div class="row">
  
                      <!-- First column -->
                      <div class="col-md-12 mt-4">
                        <div class="form-group textarea">
                          <label for="id_about" class="textarea-label"> About me</label>
                          <textarea type="id_about" id="id_about" name="about" class="textarea md-textarea form-control" rows="3">{% if user.profile.about %}{{user.profile.about}} {% else %} {% endif %}</textarea>
                        </div>
                      </div>
                    </div>
                    <!-- Third row -->
                    
                    <!-- Fourth row -->
                    <div class="row">
                      <div class="col-md-12 text-center my-4">
                        <span class="waves-input-wrapper"><input type="submit" value="Update Account" class="btn crose-btn bg-info"></span>
                      </div>
                    </div>
                    <!-- Fourth row -->
  
                </form>
            </div>
        </div>
        </div>
        <!-- work -->
        
    </div>
    
</div>

{% endblock %}