ngo/urls.py
from django.urls import path, include
from .views import *

app_name = "ngo"
urlpatterns = [
    path('', index, name="index"),
    path('about/', about, name="about"),
    path('contact/', contact, name="contact"),
    path('events/', events, name="events"),
    path('event/<slug:slug>/', event_details, name="event"),
    path('blog/', blog, name="blog"),
    path('blog/<slug:slug>/', post_details, name="post"),
    path('projects/', projects, name="projects"),
    path('project/<slug:slug>/', project_details, name="project"),
    path('search/', search, name="search"),
    path('gallery/', gallery, name="gallery"),
    path('become-a-member/', join, name="join"),
    path('subscribe/', subscribe, name="subscribe"),
    path('unsubscribe/<email>/', unsubscribe, name="unsubscribe"),
]

vauth/urls.py
from django.urls import path, re_path
from .views import *

app_name = "vauth"
urlpatterns = [
    path('login/', mylogin, name="login"),
    path('dashboard/', dashboard, name="dashboard"),
    path('analytics/', analytics, name="analytics"),
    path('profile/', profile, name="profile"),
    path('dp/', dp, name="dp"),
    path('posts/', posts, name="posts"),
    path('edit-post/<slug:slug>/', edit_post, name="edit_post"),
    path('tasks/', tasks, name="tasks"),
    path('complete-task/<int:task_id>/', complete_task, name="complete_task"),
    path('newsletter/', newsletter, name="newsletter"),
    path('ajax-donations/', ajax_donations, name="ajax_donations"),
    path("ajax-visitors/", ajax_visitors, name="ajax_visitors"),
    #####################
    re_path(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
]

ngo/models.py
from django.db import models
from django.shortcuts import reverse, redirect
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.db.models.signals import pre_save
from ckeditor.fields import RichTextField
from .utils import image_resize

TYPES = (
    ('P', 'Post'),
    ('PR', 'Project')
)

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    cat_type = models.CharField(max_length=100, choices=TYPES)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("ngo:category", kwargs={"slug": self.slug})
    class Meta:
        verbose_name_plural = "Categories"

class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    tags = TaggableManager()
    content = RichTextField()
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    cover = models.ImageField(upload_to="posts/")
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("ngo:post", kwargs={"slug": self.slug})
    class Meta:
        ordering  = ['-created']
    
    def save(self, *args, **kwargs):
        image_resize(self.cover, 950,950)
        super().save(*args, **kwargs)
    

class Event(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    tags = TaggableManager()
    content = RichTextField()
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    due_datetime = models.DateTimeField(blank=True, null=True)
    location = models.CharField(max_length=100, blank=True, null=True)
    embed_script = models.CharField(max_length=255, blank=True, null=True)
    cover = models.ImageField(upload_to="events/")

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("ngo:event", kwargs={"slug": self.slug})
    class Meta:
        ordering  = ['-due_datetime']

    def save(self, *args, **kwargs):
        image_resize(self.cover, 950,950)
        super().save(*args, **kwargs)


class Project(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    tags = TaggableManager()
    content = RichTextField()
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    cover = models.ImageField(upload_to="projects/")
    raised = models.FloatField()
    goal = models.FloatField()

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("ngo:project", kwargs={"slug": self.slug})
    class Meta:
        ordering  = ['-created']

    def save(self, *args, **kwargs):
        image_resize(self.cover, 950,950)
        super().save(*args, **kwargs)

class Image(models.Model):
    name = models.CharField(max_length=100)
    source = models.ImageField()
    description = models.TextField()
    published = models.DateTimeField(auto_now_add=True, db_index=True)
    def __str__(self):
        return self.name
    class Meta:
        ordering  = ['-published']

    def save(self, *args, **kwargs):
        image_resize(self.source, 950,950)
        super().save(*args, **kwargs)

class Subscriber(models.Model):
    email = models.EmailField(max_length=254, unique=True)

# def post_reciever(sender, instance, created, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = instance.title.replace(' ', '-').strip("('')").lower()

# pre_save.connect(post_reciever, sender=User)
# def save(self, *args, **kwargs):
#     try:
#         this = MyModelName.objects.get(id=self.id)
#         if this.MyImageFieldName != self.MyImageFieldName:
#             this.MyImageFieldName.delete()
#     except: pass
#     super(MyModelName, self).save(*args, **kwargs)

vauth/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from taggit.models import Tag
from chat.models import Contact
from ckeditor.fields import RichTextField
from .utils import user_signal, get_client_ip


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    verified = models.BooleanField(default=False)
    sex = models.CharField(max_length=10)
    about = models.TextField(blank=True, null=True)
    phone_number = models.CharField(max_length=12, blank=True, null=True)
    dp = models.ImageField(upload_to="display_pics/", blank=True, null=True)
    location = models.CharField(max_length=100)
    position = models.CharField(max_length=100, default="Member", blank=True, null=True)
    date_joined = models.DateTimeField(auto_now_add=True, db_index=True)
    subscribed = models.BooleanField(default=False, blank=True)
    class Meta:
        ordering = ['-date_joined']
    def delete(self, *args, **kwargs):
        self.dp.delete()
        super().delete(*args, **kwargs)
    # def save(self, *args, **kwargs):
    #     super().full_clean(*args, **kwargs)
    #     super().save(*args, **kwargs)


class Applicant(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    statement = models.TextField()
    middle_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, unique=True)
    phone_number = models.CharField(max_length=12, blank=True, null=True)
    address = models.CharField(max_length=100)
    sex = models.CharField(max_length=10)
    date_applied = models.DateTimeField(auto_now_add=True, db_index=True)
    class Meta:
        ordering = ['-date_applied']

class Task(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True, db_index=True)
    completed = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    class Meta:
        ordering = ['-timestamp']

def profile_reciever(sender, instance, created, *args, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        Contact.objects.create(user=instance)


post_save.connect(profile_reciever, sender=User)

# class Visitor(models.Model):
#     user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
#     ip_address = models.CharField(max_length=120)
#     timestamp = models.DateTimeField(auto_now_add=True)

# def user_receiver(sender, instance, request, *args, **kwargs):
#     user = instance
#     ip_address = get_client_ip(request)
#     ip_qs = Visitor.objects.filter(ip_address=ip_address)
#     if not ip_qs.exists():
#         user_session = Visitor.objects.create(ip_address=ip_address)
#         if user.is_authenticated:
#             print(Visitor.objects.exists())
#             if Visitor.objects.exists():
#                 if not Visitor.objects.filter(user=user).exists():
#                     user_session.user = user
#         user_session.save()

# user_signal.connect(user_receiver)

ngo/forms.py
from django import forms
from .models import Subscriber
from vauth.models import Applicant
from django.forms import ModelForm
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _

class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField(widget=forms.NumberInput())
    message = forms.CharField(widget=forms.TextInput())

SEX = (
    ('male','male'),
    ('female', 'female')
)

class ApplicantForm(ModelForm):
    sex = forms.ChoiceField(choices=SEX)
    class Meta:
        model = Applicant
        exclude = ['date_applied']
        error_messages = {
            'email': {
                'unique': _("Sorry Someone has already applied using this email."),
            },
        }

class SubscriberForm(ModelForm):
    class Meta:
        model = Subscriber
        fields = '__all__'
        

vauth/forms.py
from django import forms
from .validators import validate_file_extension
from django.contrib.auth.models import User
from django.forms import ModelForm
from ngo.views import Post
from ckeditor.widgets import CKEditorWidget

class ProfileForm(ModelForm):
    location = forms.CharField(required=False)
    about = forms.CharField(required=False, widget=forms.Textarea())
    phone_number = forms.CharField(required=False)
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']
    def save(self, commit=True):
        user = self.instance
        user.profile.location = self.cleaned_data['location']
        user.profile.about = self.cleaned_data['about']
        user.profile.phone_number = self.cleaned_data['phone_number']
        user.profile.save()
        if commit:
            return super(ProfileForm, self).save()



    # def clean(self):
    #     cleaned_data = super().clean()
    #     username = cleaned_data.get("username")
    #     users = User.objects.all()
    #     if username and subject and "help" not in subject:
    #         msg = "Must put 'help' in subject when cc'ing yourself."
    #         self.add_error('username', msg)
    #         self.add_error('subject', msg)
    
class PostForm(ModelForm):
    content = forms.CharField(widget=CKEditorWidget())
    cover = forms.ImageField(validators=[validate_file_extension], required=False)
    class Meta:
        model = Post
        # fields = [ 'title', 'tags', 'quote', 'content', 'cover', 'category']
        exclude = ['created', 'slug', 'author']

class NewsletterForm(forms.Form):
    title = forms.CharField()
    body = forms.CharField(widget=CKEditorWidget())

class PictureForm(forms.Form):
    picture = forms.ImageField(validators=[validate_file_extension])

class LoginForm(forms.Form):
    username= forms.CharField()
    password = forms.CharField(widget=(forms.PasswordInput()))
    remember = forms.CharField(widget=(forms.CheckboxInput))

templates/ngo/contact.html
{% extends 'ngo/base.html' %}
{% load static %}
{% load admintag %}
{% block title %}Contact{% endblock title %}
{% block body %}

    <!-- ##### Breadcrumb Area Start ##### -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Contact</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcrumb Area End ##### -->

    <!-- ##### Google Maps Start ##### -->
    <div class="map-area mt-30">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3949.7791558078357!2d5.081194314825962!3d8.123953604742422!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x104820481540fac1%3A0xb324dd3eec5f181b!2sLandmark%20University!5e0!3m2!1sen!2sng!4v1592414665964!5m2!1sen!2sng" allowfullscreen></iframe>
        {% comment %} <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d22236.40558254599!2d-118.25292394686001!3d34.057682914027104!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2c75ddc27da13%3A0xe22fdf6f254608f4!2z4Kay4Ka4IOCmj-CmnuCnjeCmnOCnh-CmsuCnh-CmuCwg4KaV4KeN4Kav4Ka-4Kay4Ka_4Kar4KeL4Kaw4KeN4Kao4Ka_4Kav4Ka84Ka-LCDgpq7gpr7gprDgp43gppXgpr_gpqgg4Kav4KeB4KaV4KeN4Kak4Kaw4Ka-4Ka34KeN4Kaf4KeN4Kaw!5e0!3m2!1sbn!2sbd!4v1532328708137" allowfullscreen></iframe> {% endcomment %}
    </div>
    <!-- ##### Google Maps End ##### -->

    <!-- ##### Contact Area Start ##### -->
    <section class="contact-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="contact-content-area">
                        <div class="row">
                            <div class="col-12 col-md-6">
                                <div class="contact-content contact-information">
                                    <h4>Contact</h4>
                                    <p>{% website_email %}</p>
                                    <p>{% phone_number %}</p>
                                </div>
                            </div>
                            <div class="col-12 col-md-6">
                                <div class="contact-content contact-information">
                                    <h4>Address</h4>
                                    <p>{% address %}</p>
                                    <p>{% state_country %}</p>
                                </div>
                            </div>
                            {% comment %} <div class="col-12 col-md-4">
                                <div class="contact-content contact-information">
                                    <h4>Opening Hours</h4>
                                    <p>Mon-Sat: 10 Am to 6 Pm</p>
                                    <p>Sunday: Close</p>
                                </div>
                            </div> {% endcomment %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Contact Area End ##### -->

    <!-- ##### Contact Form Area Start ##### -->
    <div class="contact-form section-padding-0-100">
        <div class="container">
            <div class="row">
                <!-- Section Heading -->
                <div class="col-12">
                    <div class="section-heading">
                        <h2>Leave A Message</h2>
                        <p>Your email address will not be published. Required fields are marked.</p>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12">
                    <!-- Contact Form Area -->
                    <div class="contact-form-area">
                        <form action="{% url 'ngo:contact' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-12 col-lg-4">
                                    <div class="form-group">
                                        <label for="contact-name">Full Name*:</label>
                                        <input type="text" class="form-control" name="name" id="id_name" placeholder="Full Name" required>
                                    </div>
                                </div>
                                <div class="col-12 col-lg-4">
                                    <div class="form-group">
                                        <label for="contact-email">Email*:</label>
                                        <input type="email" class="form-control" name="email" id="id_email" placeholder="you@gmail.com" required>
                                    </div>
                                </div>
                                <div class="col-12 col-lg-4">
                                    <div class="form-group">
                                        <label for="contact-number">Phone*:</label>
                                        <input type="text" class="form-control" name="phone" id="id_phone" placeholder="(+12) 123 456 7910" required>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-group">
                                        <label for="message">Message*:</label>
                                        <textarea class="form-control" name="message" id="id_message" cols="30" rows="10" placeholder="Message" required></textarea>
                                    </div>
                                </div>
                                <div class="col-12 text-center">
                                    <button type="submit" class="btn crose-btn mt-15">Submit Now</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Contact Form Area End ##### -->

{% endblock %}

templates/ngo/join.html
{% extends 'ngo/base.html' %}
{% load static %}
{% load filter %}
{% block title %}Become A Member{% endblock title %}
{% block body %}

    <!-- ##### Breadcrumb Area Start ##### -->
    <div class="breadcrumb-area">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="#"><i class="fa fa-home"></i> Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Become a member</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Breadcrumb Area End ##### -->

<!-- Application area -->
<div class="container">
    <div class="card mt-4 mb-4">
        <div class="card-body">
            <h2 class="text-center mt-2 mb-4">Apply Here</h2>
            <hr>
            <div class="row">
                <div class="col-md-6">
                  <div class="container">
                    <h4 class="text-center">Terms Of Use</h4>
                
                    {% lorem 3 p random %}

                  </div>
                </div>
                <div class="col-md-6">
                    <h4 class="text-center">Your Details</h4>
                    <form action="{% url 'ngo:join' %}" method="post" class="contact-form-area mine">
                    {% csrf_token %}
                            <!-- First row -->
                            <div class="row">
          
                              <!-- First column -->
                              <div class="col-md-6">
                                <div class="form-group">
                                  <input type="text" id="id_first_name" name="first_name" class="form-control validate" placeholder="First Name" autofocus required>
                                  {% if form.errors %}
                                  {% for error in form.first_name.errors %}<small class="text-danger">{{error}}</small>{% endfor %}
                                  {% endif %}
                                </div>
                              </div>
                              <!-- Second column -->
                              <div class="col-md-6">
                                <div class="form-group">
                                  <input type="text" id="last_name" name="last_name" class="form-control validate"  placeholder="Last Name" required>
                                  {% if form.errors %}
                                  {% for error in form.last_name.errors %}<small class="text-danger">{{error}}</small>{% endfor %}
                                  {% endif %}
                                </div>
                              </div>
                            </div>
                            <!-- First row -->
          
                            <!-- First row -->
                            <div class="row">
                              <!-- First column -->
                              <div class="col-md-6">
                                <div class="form-group">
                                  <input type="text" id="id_middle_name" name="middle_name" class="form-control validate" placeholder="Middle Name" required>
                                  {% if form.errors %}
                                  {% for error in form.middle_name.errors %}<small class="text-danger">{{error}}</small>{% endfor %}
                                  {% endif %}
                                </div>
                              </div>
                              <div class="col-md-6">
                                <div class="form-group">
                                  <select type="text" id="id_sex" name="sex" class="form-control validate" required>
                                    <option value="male">Male</option>
                                    <option value="female">Female</option>
                                  </select>
                                  {% if form.errors %}
                                  {% for error in form.sex.errors %}<small class="text-danger">{{error}}</small>{% endfor %}
                                  {% endif %}
                                </div>
                              </div>
          
                              <!-- Second column -->
                              <div class="col-md-12">
                                <div class="form-group">
                                  <input type="email" id="id_email" name="email" class="form-control validate" placeholder="Email" required>
                                  {% if form.errors %}
                                  {% for error in form.email.errors %}<small class="text-danger">{{error}}</small>{% endfor %}
                                  {% endif %}
                                </div>
                              </div>
                            </div>
                            <!-- First row -->
          
                            <!-- Second row -->
                            <div class="row">
          
                              <!-- First column -->
                              <div class="col-md-12">
                                <div class="form-group">
                                  <input type="tel" id="id_phone_number" name="phone_number" class="form-control validate" placeholder="Phone Number" required>
                                </div>
                                  {% if form.errors %}
                                  {% for error in form.phone_number.errors %}<small class="text-danger">{{error}}</small>{% endfor %}
                                  {% endif %}
                              </div>
                              <!-- Second column -->
          
                              <div class="col-md-12">
                                <div class="form-group">
                                  <input type="text" id="id_address" name="address" class="form-control validate" placeholder="Address" required>
                                  {% if form.errors %}
                                  {% for error in form.address.errors %}<small class="text-danger">{{error}}</small>{% endfor %}
                                  {% endif %}
                                </div>
                              </div>
                            </div>
                            <!-- Second row -->
          
                            <!-- Third row -->
                            <div class="row">
          
                              <!-- First column -->
                              <div class="col-md-12 mt-4">
                                <div class="form-group textarea">
                                  <textarea type="text" id="id_statement" name="statement" class="form-control" rows="3" required placeholder="Statement"></textarea>
                                  {% if form.errors %}
                                  {% for error in form.statement.errors %}<small class="text-danger">{{error}}</small>{% endfor %}
                                  {% endif %}
                                </div>
                              </div>
                            </div>
                            <!-- Third row -->
          
                            <!-- Fourth row -->
                            <div class="row">
                              <div class="col-md-12 text-center my-4">
                              <input type="submit" value="Apply" class="btn crose-btn">
                              </div>
                            </div>
                            <!-- Fourth row -->
                    </form>
                </div>
            </div>
        </div>

    </div>
</div>
<!-- Application area -->

{% endblock %}